server:
   port: 8000
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/olx-users
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Temp1234
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect#   application:#     name: auth-service
#     
eureka:  client:
    register-with-eureka: true
    fetch-registry: true  instance:    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}     
